# Generated by Django 3.2.13 on 2022-06-11 00:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('simplelist', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='simplelistpage',
            name='app_store_url',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='simplelistpage',
            name='gplay_url',
            field=models.URLField(blank=True, null=True),
        ),
    ]
