# Generated by Django 3.2.13 on 2022-06-11 00:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('simplelist', '0002_auto_20220611_0021'),
    ]

    operations = [
        migrations.AddField(
            model_name='simplelistpage',
            name='hero_changing_words',
            field=models.CharField(default='útil, todo terreno', help_text="Separadas por ','", max_length=100, verbose_name='Secuencia de palabras'),
        ),
        migrations.AddField(
            model_name='simplelistpage',
            name='hero_subtitle',
            field=models.CharField(default='Simple list te permitirá llevar el calculo de tu compra en todo momento', max_length=30, verbose_name='Subtítulo'),
        ),
        migrations.AddField(
            model_name='simplelistpage',
            name='hero_title',
            field=models.CharField(default='Simple list', max_length=50, verbose_name='Título'),
        ),
        migrations.AlterField(
            model_name='simplelistpage',
            name='app_store_url',
            field=models.URLField(blank=True, null=True, verbose_name='URL App store'),
        ),
        migrations.AlterField(
            model_name='simplelistpage',
            name='gplay_url',
            field=models.URLField(blank=True, null=True, verbose_name='URL de Google Play'),
        ),
    ]
