# Generated by Django 3.2.13 on 2022-06-11 00:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('simplelist', '0003_auto_20220611_0029'),
    ]

    operations = [
        migrations.AlterField(
            model_name='simplelistpage',
            name='description',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='simplelistpage',
            name='hero_subtitle',
            field=models.CharField(default='Simple list te permitirá llevar el calculo de tu compra en todo momento', max_length=100, verbose_name='Subtítulo'),
        ),
    ]
