# Generated by Django 3.2.13 on 2022-06-11 00:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('simplelist', '0004_auto_20220611_0030'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='simplelistpage',
            name='description',
        ),
    ]
