# Generated by Django 3.2.13 on 2022-06-11 18:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('simplelist', '0005_remove_simplelistpage_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='simplelistpage',
            name='title_section1',
            field=models.CharField(default='', max_length=50),
        ),
    ]
