# Generated by Django 3.2.13 on 2022-06-11 18:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('simplelist', '0007_auto_20220611_1846'),
    ]

    operations = [
        migrations.RenameField(
            model_name='simplelistpage',
            old_name='title_description1',
            new_name='description_section1',
        ),
    ]
