# Generated by Django 3.2.13 on 2022-06-11 18:52

from django.db import migrations, models
import wagtail.core.fields


class Migration(migrations.Migration):

    dependencies = [
        ('simplelist', '0008_rename_title_description1_simplelistpage_description_section1'),
    ]

    operations = [
        migrations.AddField(
            model_name='simplelistpage',
            name='description_section2',
            field=wagtail.core.fields.RichTextField(default='', verbose_name='Descripción sección 2'),
        ),
        migrations.AddField(
            model_name='simplelistpage',
            name='title_section2',
            field=models.CharField(default='', max_length=50, verbose_name='Titulo sección 2'),
        ),
        migrations.AlterField(
            model_name='simplelistpage',
            name='description_section1',
            field=wagtail.core.fields.RichTextField(default='', verbose_name='Descripción sección 1'),
        ),
    ]
