# Generated by Django 3.2.13 on 2022-06-11 19:08

from django.db import migrations, models
import wagtail.core.fields


class Migration(migrations.Migration):

    dependencies = [
        ('simplelist', '0009_auto_20220611_1852'),
    ]

    operations = [
        migrations.AddField(
            model_name='simplelistpage',
            name='description_section3',
            field=wagtail.core.fields.RichTextField(default='', verbose_name='Descripción sección 2'),
        ),
        migrations.AddField(
            model_name='simplelistpage',
            name='subtitle_section3',
            field=models.CharField(default='', max_length=50, verbose_name='Subtítulo sección 3'),
        ),
        migrations.AddField(
            model_name='simplelistpage',
            name='title_section3',
            field=models.CharField(default='', max_length=50, verbose_name='Titulo sección 2'),
        ),
    ]
