# Generated by Django 3.2.13 on 2022-06-11 19:22

from django.db import migrations, models
import wagtail.core.blocks
import wagtail.core.fields


class Migration(migrations.Migration):

    dependencies = [
        ('simplelist', '0011_auto_20220611_1915'),
    ]

    operations = [
        migrations.AddField(
            model_name='simplelistpage',
            name='footer_desc',
            field=models.TextField(default='', verbose_name='Descripción del footer'),
        ),
        migrations.AddField(
            model_name='simplelistpage',
            name='footer_link_label',
            field=models.CharField(default='Enlaces', max_length=20, verbose_name='Etiqueta enlace'),
        ),
        migrations.AddField(
            model_name='simplelistpage',
            name='footer_title',
            field=models.CharField(default='', max_length=20, verbose_name='Título del footer'),
        ),
        migrations.AddField(
            model_name='simplelistpage',
            name='footer_urls',
            field=wagtail.core.fields.StreamField([('urls', wagtail.core.blocks.ListBlock(wagtail.core.blocks.URLBlock()))], default=''),
        ),
    ]
