# Generated by Django 3.2.13 on 2022-06-11 19:24

from django.db import migrations, models
import wagtail.core.blocks
import wagtail.core.fields


class Migration(migrations.Migration):

    dependencies = [
        ('simplelist', '0012_auto_20220611_1922'),
    ]

    operations = [
        migrations.AlterField(
            model_name='simplelistpage',
            name='download_caption',
            field=models.CharField(blank=True, default='', max_length=80, null=True, verbose_name='Descripción descarga'),
        ),
        migrations.AlterField(
            model_name='simplelistpage',
            name='footer_urls',
            field=wagtail.core.fields.StreamField([('urls', wagtail.core.blocks.ListBlock(wagtail.core.blocks.URLBlock()))], blank=True, default='', null=True),
        ),
    ]
