# Generated by Django 3.2.13 on 2022-06-11 19:48

from django.db import migrations
import wagtail.core.blocks
import wagtail.core.fields


class Migration(migrations.Migration):

    dependencies = [
        ('simplelist', '0013_auto_20220611_1924'),
    ]

    operations = [
        migrations.AlterField(
            model_name='simplelistpage',
            name='footer_urls',
            field=wagtail.core.fields.StreamField([('urls', wagtail.core.blocks.URLBlock())], blank=True, default='', null=True),
        ),
    ]
