# Generated by Django 3.2.13 on 2022-06-11 19:50

from django.db import migrations
import wagtail.core.blocks
import wagtail.core.fields


class Migration(migrations.Migration):

    dependencies = [
        ('simplelist', '0014_alter_simplelistpage_footer_urls'),
    ]

    operations = [
        migrations.AlterField(
            model_name='simplelistpage',
            name='footer_urls',
            field=wagtail.core.fields.StreamField([('label', wagtail.core.blocks.CharBlock(max_length=50)), ('urls', wagtail.core.blocks.URLBlock())], blank=True, default='', null=True),
        ),
    ]
