# Generated by Django 3.2.13 on 2022-06-11 19:55

from django.db import migrations, models
import wagtail.core.blocks
import wagtail.core.fields


class Migration(migrations.Migration):

    dependencies = [
        ('simplelist', '0016_alter_simplelistpage_footer_urls'),
    ]

    operations = [
        migrations.AddField(
            model_name='simplelistpage',
            name='footer_copyright',
            field=models.CharField(blank=True, default='', max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='simplelistpage',
            name='footer_urls',
            field=wagtail.core.fields.StreamField([('url', wagtail.core.blocks.StructBlock([('label', wagtail.core.blocks.CharBlock(label='Etiqueta', max_length=50)), ('urls', wagtail.core.blocks.URLBlock(label='URL'))], label='URL'))], blank=True, default='', null=True),
        ),
    ]
