# Generated by Django 3.2.13 on 2022-06-12 00:23

from django.db import migrations
import wagtail.core.fields


class Migration(migrations.Migration):

    dependencies = [
        ('simplelist', '0018_termspage'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='termspage',
            options={'verbose_name': 'Página de terminos'},
        ),
        migrations.AlterField(
            model_name='termspage',
            name='content',
            field=wagtail.core.fields.RichTextField(verbose_name='Contenido'),
        ),
    ]
