# Generated by Django 3.2.13 on 2022-06-12 00:34

from django.db import migrations, models
import django.db.models.deletion
import wagtail.core.blocks
import wagtail.core.fields


class Migration(migrations.Migration):

    dependencies = [
        ('wagtailcore', '0066_collection_management_permissions'),
        ('simplelist', '0019_auto_20220612_0023'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='simplelistpage',
            name='footer_desc',
        ),
        migrations.RemoveField(
            model_name='simplelistpage',
            name='footer_link_label',
        ),
        migrations.RemoveField(
            model_name='simplelistpage',
            name='footer_title',
        ),
        migrations.RemoveField(
            model_name='simplelistpage',
            name='footer_urls',
        ),
        migrations.CreateModel(
            name='FooterSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('footer_title', models.CharField(default='', max_length=20, verbose_name='Título del footer')),
                ('footer_desc', models.TextField(default='', verbose_name='Descripción del footer')),
                ('footer_link_label', models.CharField(default='Enlaces', max_length=20, verbose_name='Etiqueta enlace')),
                ('footer_urls', wagtail.core.fields.StreamField([('url', wagtail.core.blocks.StructBlock([('label', wagtail.core.blocks.CharBlock(label='Etiqueta', max_length=50)), ('urls', wagtail.core.blocks.URLBlock(label='URL'))], label='URL'))], blank=True, default='', null=True)),
                ('site', models.OneToOneField(editable=False, on_delete=django.db.models.deletion.CASCADE, to='wagtailcore.site')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
