# Generated by Django 3.2.13 on 2022-06-12 00:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('simplelist', '0020_auto_20220612_0034'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='footersettings',
            options={'verbose_name': 'Datos del pie de página'},
        ),
        migrations.RemoveField(
            model_name='simplelistpage',
            name='footer_copyright',
        ),
        migrations.AddField(
            model_name='footersettings',
            name='footer_copyright',
            field=models.CharField(blank=True, default='', max_length=50, null=True),
        ),
    ]
