# Generated by Django 3.2.13 on 2022-06-12 00:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('simplelist', '0021_auto_20220612_0037'),
    ]

    operations = [
        migrations.AddField(
            model_name='footersettings',
            name='footer_email',
            field=models.EmailField(default='myemail@email.com', max_length=254),
        ),
    ]
